import './globals.css'
import { Inter } from 'next/font/google'
import { i18n } from '../../i18n-config'
import Providers from './components/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  metadataBase: new URL('https://example.com'),
  alternates: {
    canonical: '/',
    // languages: {
    //   'en-US': '/en-US',
    //   'de-DE': '/de-DE',
    // },
  },
  openGraph: {
    images: '/og-image.png',
  },
}

// export async function generateStaticParams() {
//   return i18n.locales.map((locale) => ({ lang: locale }))
// }

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode,
  params: { lang: string }
}) {
  return (
    <Providers>
      <html lang={params.lang}>
        <body className={inter.className}>
          <h1>Root layout</h1>
          {children}
          </body>
      </html>
    </Providers>
  )
}
